services:
  # Сервис для фронтенда (React с Vite)
  frontend:
    build:
      context: ./frontend-lab2  # Путь к папке с исходниками фронтенда
      dockerfile: Dockerfile  # Указание на Dockerfile для фронтенда
    ports:
      - "5173:80"  # Прокси порт для доступа к фронтенду через HTTP
    depends_on:
      - backend  # Фронтенд будет запускаться после бэкенда
    networks:
      - app-network

  # Сервис для бэкенда (Spring Boot)
  backend:
    build:
      context: backend-lab2  # Путь к папке с исходниками бэкенда
      dockerfile: Dockerfile  # Указание на Dockerfile для бэкенда
    ports:
      - "8080:8080"  # Прокси порт для доступа к бэкенду
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/is-lab1-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db  # Бэкенд будет запускаться после базы данных
    networks:
      - app-network

  # Сервис для базы данных (PostgreSQL)
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=is-lab1-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MAX_CONNECTIONS=300  # Увеличиваем максимальное количество подключений
    ports:
      - "5432:5432"  # Прокси порт для доступа к БД
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Добавление volume для сохранения данных
    networks:
      - app-network

  # S3 хранилище
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=admin  # Ключ доступа MinIO
      - MINIO_SECRET_KEY=12345678  # Секретный ключ MinIO
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/minio
    command: server ~/minio --console-address :9090 # Команда для запуска MinIO с использованием тома для данных
    networks:
      - app-network

# Определение volume
volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  app-network:
    driver: bridge
